Traceback (most recent call last):
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/markus/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/markus/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_stats = pd.concat([df, dummies[["Ocean_Prox_INLAND","priceCat_below"]]], axis=1)
df_stats = df_stats.drop(columns=["Ocean_Prox", "priceCat"], axis=1)
numeric_feature_names = df_stats.drop(columns=["Ocean_Prox_INLAND", "priceCat_below", "median_house_value"],axis=1).columns
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/8p/j79wt3gs4478j15_gm54gfg40000gn/T/ipykernel_3682/1709389668.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf_stats[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mconcat[0m[0;34m([0m[0;34m[[0m[0mdf[0m[0;34m,[0m [0mdummies[0m[0;34m[[0m[0;34m[[0m[0;34m"Ocean_Prox_INLAND"[0m[0;34m,[0m[0;34m"priceCat_below"[0m[0;34m][0m[0;34m][0m[0;34m][0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mdf_stats[0m [0;34m=[0m [0mdf_stats[0m[0;34m.[0m[0mdrop[0m[0;34m([0m[0mcolumns[0m[0;34m=[0m[0;34m[[0m[0;34m"Ocean_Prox"[0m[0;34m,[0m [0;34m"priceCat"[0m[0;34m][0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mnumeric_feature_names[0m [0;34m=[0m [0mdf_stats[0m[0;34m.[0m[0mdrop[0m[0;34m([0m[0mcolumns[0m[0;34m=[0m[0;34m[[0m[0;34m"Ocean_Prox_INLAND"[0m[0;34m,[0m [0;34m"priceCat_below"[0m[0;34m,[0m [0;34m"median_house_value"[0m[0;34m][0m[0;34m,[0m[0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m.[0m[0mcolumns[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'dummies' is not defined
NameError: name 'dummies' is not defined

